language: python
python:
  - "3.6"
  - "3.7"
# command to install dependencies
install:
  - pip3 install torch==1.3.0+cpu torchvision==0.4.1+cpu -f https://download.pytorch.org/whl/torch_stable.html
  - pip install -r requirements.txt
#before_script:
#  - export PYTHONPATH="/home/travis/build/buwantaiji/DominantSparseEigenAD"
# command to run tests
script:
  - pytest
